#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: tailscale/tailscale
  # -- image tag
  tag: v1.21.82
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [tailscale documentation](https://tailscale.org/docs).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  USERSPACE: "true"
  AUTH_KEY: foobar


ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence: {}
  # data:
  #   enabled: false
  #   mountPath: /data
